/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LeaguesIndexRouteImport } from './routes/leagues/index'
import { Route as LeaguesJoinRouteImport } from './routes/leagues/join'
import { Route as LeaguesNewRouteImport } from './routes/leagues/new'
import { Route as PracticeNewRouteImport } from './routes/practice/new'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamNumberRouteImport } from './routes/teams/$teamNumber'
import { Route as LeaguesLeagueIdIndexRouteImport } from './routes/leagues/$leagueId/index'
import { Route as LeaguesLeagueIdDraftRouteImport } from './routes/leagues/$leagueId/draft'
import { Route as LeaguesLeagueIdSettingsRouteImport } from './routes/leagues/$leagueId/settings'
import { Route as LeaguesLeagueIdStandingsRouteImport } from './routes/leagues/$leagueId/standings'
import { Route as LeaguesLeagueIdTradesRouteImport } from './routes/leagues/$leagueId/trades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesJoinRoute = LeaguesJoinRouteImport.update({
  id: '/leagues/join',
  path: '/leagues/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesNewRoute = LeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeNewRoute = PracticeNewRouteImport.update({
  id: '/practice/new',
  path: '/practice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamNumberRoute = TeamsTeamNumberRouteImport.update({
  id: '/teams/$teamNumber',
  path: '/teams/$teamNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdIndexRoute = LeaguesLeagueIdIndexRouteImport.update({
  id: '/leagues/$leagueId/',
  path: '/leagues/$leagueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdDraftRoute = LeaguesLeagueIdDraftRouteImport.update({
  id: '/leagues/$leagueId/draft',
  path: '/leagues/$leagueId/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdSettingsRoute = LeaguesLeagueIdSettingsRouteImport.update({
  id: '/leagues/$leagueId/settings',
  path: '/leagues/$leagueId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesLeagueIdStandingsRoute =
  LeaguesLeagueIdStandingsRouteImport.update({
    id: '/leagues/$leagueId/standings',
    path: '/leagues/$leagueId/standings',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeaguesLeagueIdTradesRoute = LeaguesLeagueIdTradesRouteImport.update({
  id: '/leagues/$leagueId/trades',
  path: '/leagues/$leagueId/trades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/leagues/new': typeof LeaguesNewRoute
  '/practice/new': typeof PracticeNewRoute
  '/teams/$teamNumber': typeof TeamsTeamNumberRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/leagues/$leagueId/draft': typeof LeaguesLeagueIdDraftRoute
  '/leagues/$leagueId/settings': typeof LeaguesLeagueIdSettingsRoute
  '/leagues/$leagueId/standings': typeof LeaguesLeagueIdStandingsRoute
  '/leagues/$leagueId/trades': typeof LeaguesLeagueIdTradesRoute
  '/leagues/$leagueId/': typeof LeaguesLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/leagues/new': typeof LeaguesNewRoute
  '/practice/new': typeof PracticeNewRoute
  '/teams/$teamNumber': typeof TeamsTeamNumberRoute
  '/leagues': typeof LeaguesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/leagues/$leagueId/draft': typeof LeaguesLeagueIdDraftRoute
  '/leagues/$leagueId/settings': typeof LeaguesLeagueIdSettingsRoute
  '/leagues/$leagueId/standings': typeof LeaguesLeagueIdStandingsRoute
  '/leagues/$leagueId/trades': typeof LeaguesLeagueIdTradesRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/leagues/join': typeof LeaguesJoinRoute
  '/leagues/new': typeof LeaguesNewRoute
  '/practice/new': typeof PracticeNewRoute
  '/teams/$teamNumber': typeof TeamsTeamNumberRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/leagues/$leagueId/draft': typeof LeaguesLeagueIdDraftRoute
  '/leagues/$leagueId/settings': typeof LeaguesLeagueIdSettingsRoute
  '/leagues/$leagueId/standings': typeof LeaguesLeagueIdStandingsRoute
  '/leagues/$leagueId/trades': typeof LeaguesLeagueIdTradesRoute
  '/leagues/$leagueId/': typeof LeaguesLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/join'
    | '/leagues/new'
    | '/practice/new'
    | '/teams/$teamNumber'
    | '/leagues/'
    | '/teams/'
    | '/leagues/$leagueId/draft'
    | '/leagues/$leagueId/settings'
    | '/leagues/$leagueId/standings'
    | '/leagues/$leagueId/trades'
    | '/leagues/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/join'
    | '/leagues/new'
    | '/practice/new'
    | '/teams/$teamNumber'
    | '/leagues'
    | '/teams'
    | '/leagues/$leagueId/draft'
    | '/leagues/$leagueId/settings'
    | '/leagues/$leagueId/standings'
    | '/leagues/$leagueId/trades'
    | '/leagues/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/leagues/join'
    | '/leagues/new'
    | '/practice/new'
    | '/teams/$teamNumber'
    | '/leagues/'
    | '/teams/'
    | '/leagues/$leagueId/draft'
    | '/leagues/$leagueId/settings'
    | '/leagues/$leagueId/standings'
    | '/leagues/$leagueId/trades'
    | '/leagues/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LeaguesJoinRoute: typeof LeaguesJoinRoute
  LeaguesNewRoute: typeof LeaguesNewRoute
  PracticeNewRoute: typeof PracticeNewRoute
  TeamsTeamNumberRoute: typeof TeamsTeamNumberRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  LeaguesLeagueIdDraftRoute: typeof LeaguesLeagueIdDraftRoute
  LeaguesLeagueIdSettingsRoute: typeof LeaguesLeagueIdSettingsRoute
  LeaguesLeagueIdStandingsRoute: typeof LeaguesLeagueIdStandingsRoute
  LeaguesLeagueIdTradesRoute: typeof LeaguesLeagueIdTradesRoute
  LeaguesLeagueIdIndexRoute: typeof LeaguesLeagueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/join': {
      id: '/leagues/join'
      path: '/leagues/join'
      fullPath: '/leagues/join'
      preLoaderRoute: typeof LeaguesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/new': {
      id: '/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof LeaguesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/new': {
      id: '/practice/new'
      path: '/practice/new'
      fullPath: '/practice/new'
      preLoaderRoute: typeof PracticeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamNumber': {
      id: '/teams/$teamNumber'
      path: '/teams/$teamNumber'
      fullPath: '/teams/$teamNumber'
      preLoaderRoute: typeof TeamsTeamNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId/': {
      id: '/leagues/$leagueId/'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId/'
      preLoaderRoute: typeof LeaguesLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId/draft': {
      id: '/leagues/$leagueId/draft'
      path: '/leagues/$leagueId/draft'
      fullPath: '/leagues/$leagueId/draft'
      preLoaderRoute: typeof LeaguesLeagueIdDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId/settings': {
      id: '/leagues/$leagueId/settings'
      path: '/leagues/$leagueId/settings'
      fullPath: '/leagues/$leagueId/settings'
      preLoaderRoute: typeof LeaguesLeagueIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId/standings': {
      id: '/leagues/$leagueId/standings'
      path: '/leagues/$leagueId/standings'
      fullPath: '/leagues/$leagueId/standings'
      preLoaderRoute: typeof LeaguesLeagueIdStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$leagueId/trades': {
      id: '/leagues/$leagueId/trades'
      path: '/leagues/$leagueId/trades'
      fullPath: '/leagues/$leagueId/trades'
      preLoaderRoute: typeof LeaguesLeagueIdTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LeaguesJoinRoute: LeaguesJoinRoute,
  LeaguesNewRoute: LeaguesNewRoute,
  PracticeNewRoute: PracticeNewRoute,
  TeamsTeamNumberRoute: TeamsTeamNumberRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  LeaguesLeagueIdDraftRoute: LeaguesLeagueIdDraftRoute,
  LeaguesLeagueIdSettingsRoute: LeaguesLeagueIdSettingsRoute,
  LeaguesLeagueIdStandingsRoute: LeaguesLeagueIdStandingsRoute,
  LeaguesLeagueIdTradesRoute: LeaguesLeagueIdTradesRoute,
  LeaguesLeagueIdIndexRoute: LeaguesLeagueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
